# Generated by Django 4.0.4 on 2022-05-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deskapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Titre')),
                ('description', models.TextField(max_length=2048, verbose_name='Description')),
                ('type', models.CharField(choices=[('back-end', 'Back End'), ('front-end', 'Front End'), ('iOS', 'Ios'), ('Android', 'Android')], max_length=10, verbose_name='Type')),
            ],
        ),
    ]
