# Generated by Django 4.0.4 on 2022-05-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deskapi', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2048, verbose_name='Description')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Titre')),
                ('desc', models.TextField(max_length=2048, verbose_name='Description')),
                ('tag', models.CharField(choices=[('BUG', 'Bug'), ('AMELIORATION', 'Amelioration'), ('TACHE', 'Tache')], max_length=15, verbose_name='Balise')),
                ('priority', models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYENNE', 'Moyenne'), ('ELEVEE', 'Elevee')], max_length=10, verbose_name='Priorité')),
                ('status', models.CharField(choices=[('A faire', 'A Faire'), ('En cours', 'En Cours'), ('Terminé', 'Termine')], max_length=10, verbose_name='Statut')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
